#!/bin/bash

# Prints number of todos
# Requires t todo manager (https://github.com/sjl/t)

TASKS_DIR="/home/$USER/tasks/"
TASKS_NAME="tasks"
PREFIX='t: '

get_todo()
{
echo "[$(t --task-dir $TASKS_DIR --list $TASKS_NAME | wc -l)]"
}

get_todo
