#!/bin/bash

# Prints out the volume percentage

VOLUME_ON_ICON='V:'
VOLUME_MUTED_ICON='[M]'

get_volume(){
        curStatus=$(pactl get-sink-mute @DEFAULT_SINK@)
        volume=$(pactl get-sink-volume @DEFAULT_SINK@ | tail -n 2 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' | head -n 1)
		involume=$(pactl get-source-volume @DEFAULT_SOURCE@ | tail -n 2 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' | head -n 1)
	    mpdvol=$(mpc volume | awk -F " " '{print $2}' | sed 's/%//g')

        if [ "${curStatus}" = 'Mute: yes' ]
        then
            echo "$VOLUME_MUTED_ICON"
        else
            echo "$VOLUME_ON_ICON $volume/$mpdvol/$involume"
        fi
}

get_volume
